version: 2
jobs:
  build:
    docker:
      - image: node:12.20.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - run: yarn build
      
      - run: curl -X POST -H 'Content-type: application/json' --data '{"text":"Projectx Build Complete"}' https://hooks.slack.com/services/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


